In [ ]:
print("Hello Bro 🚀")

In [1]:
print("Diabetic etinopathy and Glaucoma Detection Project")

Diabetic etinopathy and Glaucoma Detection Project

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os

print("All libraries imported successfully!")

Matplotlib is building the font cache; this may take a moment.

All libraries imported successfully!

In [3]:
import pandas as pd

# Read the CSV file
df = pd.read_csv(r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\ODIR\full_df.csv")

# Show first 5 rows
df.head()

,ID,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords,N,D,G,C,A,H,M,O,filepath,labels,target,filename
0,0,69,Female,0_left.jpg,0_right.jpg,cataract,normal fundus,0,0,0,1,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",0_right.jpg
1,1,57,Male,1_left.jpg,1_right.jpg,normal fundus,normal fundus,1,0,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",1_right.jpg
2,2,42,Male,2_left.jpg,2_right.jpg,laser spot，moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",2_right.jpg
3,4,53,Male,4_left.jpg,4_right.jpg,macular epiretinal membrane,mild nonproliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4_right.jpg
4,5,50,Female,5_left.jpg,5_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",5_right.jpg

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6392 entries, 0 to 6391
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         6392 non-null   int64
 1   Patient Age                6392 non-null   int64
 2   Patient Sex                6392 non-null   str
 3   Left-Fundus                6392 non-null   str
 4   Right-Fundus               6392 non-null   str
 5   Left-Diagnostic Keywords   6392 non-null   str
 6   Right-Diagnostic Keywords  6392 non-null   str
 7   N                          6392 non-null   int64
 8   D                          6392 non-null   int64
 9   G                          6392 non-null   int64
 10  C                          6392 non-null   int64
 11  A                          6392 non-null   int64
 12  H                          6392 non-null   int64
 13  M                          6392 non-null   int64
 14  O                          6392 non-null   int64
 15  filepath                   6392 non-null   str
 16  labels                     6392 non-null   str
 17  target                     6392 non-null   str
 18  filename                   6392 non-null   str
dtypes: int64(10), str(9)
memory usage: 2.1 MB

In [5]:
df.columns

Index(['ID', 'Patient Age', 'Patient Sex', 'Left-Fundus', 'Right-Fundus',
       'Left-Diagnostic Keywords', 'Right-Diagnostic Keywords', 'N', 'D', 'G',
       'C', 'A', 'H', 'M', 'O', 'filepath', 'labels', 'target', 'filename'],
      dtype='str')

In [6]:
import os
import shutil
import pandas as pd

In [7]:
# Read the ODIR CSV file
df = pd.read_csv(r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\ODIR\full_df.csv")

# Display first 5 rows
df.head()

,ID,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords,N,D,G,C,A,H,M,O,filepath,labels,target,filename
0,0,69,Female,0_left.jpg,0_right.jpg,cataract,normal fundus,0,0,0,1,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",0_right.jpg
1,1,57,Male,1_left.jpg,1_right.jpg,normal fundus,normal fundus,1,0,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",1_right.jpg
2,2,42,Male,2_left.jpg,2_right.jpg,laser spot，moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",2_right.jpg
3,4,53,Male,4_left.jpg,4_right.jpg,macular epiretinal membrane,mild nonproliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4_right.jpg
4,5,50,Female,5_left.jpg,5_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",5_right.jpg

In [8]:
print("Dataset Shape:", df.shape)

Dataset Shape: (6392, 19)

In [9]:
print(df.columns.tolist())

['ID', 'Patient Age', 'Patient Sex', 'Left-Fundus', 'Right-Fundus', 'Left-Diagnostic Keywords', 'Right-Diagnostic Keywords', 'N', 'D', 'G', 'C', 'A', 'H', 'M', 'O', 'filepath', 'labels', 'target', 'filename']

In [10]:
print("Normal:", df["N"].sum())
print("Diabetic Retinopathy:", df["D"].sum())
print("Glaucoma:", df["G"].sum())

Normal: 2101
Diabetic Retinopathy: 2123
Glaucoma: 397

In [ ]:
import os

# Project path
project_path = r"D:\DR AND GLAUCOMA DETECTION PROJECT"

# Final dataset path
final_dataset = os.path.join(project_path, "datasets", "Final_Dataset")

# Create folders
classes = ["normal", "diabetic_retinopathy", "glaucoma"]

for cls in classes:
    os.makedirs(os.path.join(final_dataset, cls), exist_ok=True)

print("✅ Final_Dataset folders created successfully!")

✅ Final_Dataset folders created successfully!

In [12]:
print(df.columns.tolist())

['ID', 'Patient Age', 'Patient Sex', 'Left-Fundus', 'Right-Fundus', 'Left-Diagnostic Keywords', 'Right-Diagnostic Keywords', 'N', 'D', 'G', 'C', 'A', 'H', 'M', 'O', 'filepath', 'labels', 'target', 'filename']

In [13]:
df[['filepath', 'filename']].head(10)

                                            filepath      filename
0  ../input/ocular-disease-recognition-odir5k/ODI...   0_right.jpg
1  ../input/ocular-disease-recognition-odir5k/ODI...   1_right.jpg
2  ../input/ocular-disease-recognition-odir5k/ODI...   2_right.jpg
3  ../input/ocular-disease-recognition-odir5k/ODI...   4_right.jpg
4  ../input/ocular-disease-recognition-odir5k/ODI...   5_right.jpg
5  ../input/ocular-disease-recognition-odir5k/ODI...   6_right.jpg
6  ../input/ocular-disease-recognition-odir5k/ODI...   7_right.jpg
7  ../input/ocular-disease-recognition-odir5k/ODI...   8_right.jpg
8  ../input/ocular-disease-recognition-odir5k/ODI...   9_right.jpg
9  ../input/ocular-disease-recognition-odir5k/ODI...  10_right.jpg

In [14]:
import os

training_path = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\ODIR\ODIR-5K\Training Images"
testing_path = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\ODIR\ODIR-5K\Testing Images"

print("0_right.jpg in Training:",
      os.path.exists(os.path.join(training_path, "0_right.jpg")))

print("0_right.jpg in Testing:",
      os.path.exists(os.path.join(testing_path, "0_right.jpg")))

0_right.jpg in Training: False
0_right.jpg in Testing: False

In [15]:
import os

base_path = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\ODIR\ODIR-5K"

for root, dirs, files in os.walk(base_path):
    for file in files:
        if file == "0_right.jpg":
            print("Found:", os.path.join(root, file))

Found: D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\ODIR\ODIR-5K\ODIR-5K\Training Images\0_right.jpg

In [16]:
import os
import shutil

# Correct source folder
source_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\ODIR\ODIR-5K\ODIR-5K\Training Images"

# Destination folders
normal_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset\normal"
dr_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset\diabetic_retinopathy"
glaucoma_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset\glaucoma"

normal_count = 0
dr_count = 0
glaucoma_count = 0

for _, row in df.iterrows():
    filename = row["filename"]
    source = os.path.join(source_folder, filename)

    if not os.path.exists(source):
        continue

    # Copy Normal
    if row["N"] == 1:
        shutil.copy2(source, os.path.join(normal_folder, filename))
        normal_count += 1

    # Copy Diabetic Retinopathy
    if row["D"] == 1:
        shutil.copy2(source, os.path.join(dr_folder, filename))
        dr_count += 1

    # Copy Glaucoma
    if row["G"] == 1:
        shutil.copy2(source, os.path.join(glaucoma_folder, filename))
        glaucoma_count += 1

print("✅ ODIR images copied successfully!")
print(f"Normal: {normal_count}")
print(f"Diabetic Retinopathy: {dr_count}")
print(f"Glaucoma: {glaucoma_count}")

✅ ODIR images copied successfully!
Normal: 2101
Diabetic Retinopathy: 2123
Glaucoma: 397

In [17]:
import os
import shutil

# APTOS dataset path
aptos_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\APTOS"

# Final dataset folders
normal_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset\normal"
dr_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset\diabetic_retinopathy"

normal_count = 0
dr_count = 0

# Class 0 -> Normal
class0 = os.path.join(aptos_folder, "0")
for img in os.listdir(class0):
    src = os.path.join(class0, img)
    dst = os.path.join(normal_folder, img)
    shutil.copy2(src, dst)
    normal_count += 1

# Classes 1,2,3,4 -> Diabetic Retinopathy
for cls in ["1", "2", "3", "4"]:
    class_folder = os.path.join(aptos_folder, cls)

    for img in os.listdir(class_folder):
        src = os.path.join(class_folder, img)
        dst = os.path.join(dr_folder, img)
        shutil.copy2(src, dst)
        dr_count += 1

print("✅ APTOS merged successfully!")
print(f"Normal images added: {normal_count}")
print(f"DR images added: {dr_count}")

✅ APTOS merged successfully!
Normal images added: 2000
DR images added: 8000

In [21]:
import os
import shutil

# Correct RIM-ONE path
rimone_path = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\RIM_ONE\RIM-ONE_DL_images\partitioned_randomly"

# Final dataset folders
normal_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset\normal"
glaucoma_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset\glaucoma"

normal_count = 0
glaucoma_count = 0

for dataset in ["training_set", "test_set"]:

    # Normal
    normal_src = os.path.join(rimone_path, dataset, "normal")
    for img in os.listdir(normal_src):
        shutil.copy2(
            os.path.join(normal_src, img),
            os.path.join(normal_folder, img)
        )
        normal_count += 1

    # Glaucoma
    glaucoma_src = os.path.join(rimone_path, dataset, "glaucoma")
    for img in os.listdir(glaucoma_src):
        shutil.copy2(
            os.path.join(glaucoma_src, img),
            os.path.join(glaucoma_folder, img)
        )
        glaucoma_count += 1

print("✅ RIM-ONE merged successfully!")
print(f"Normal images added: {normal_count}")
print(f"Glaucoma images added: {glaucoma_count}")

✅ RIM-ONE merged successfully!
Normal images added: 313
Glaucoma images added: 172

In [22]:
import os

base_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset"

classes = ["normal", "diabetic_retinopathy", "glaucoma"]

print("📊 Final Dataset Summary")
print("-" * 30)

total = 0

for cls in classes:
    folder = os.path.join(base_folder, cls)
    count = len([
        f for f in os.listdir(folder)
        if os.path.isfile(os.path.join(folder, f))
    ])
    print(f"{cls}: {count} images")
    total += count

print("-" * 30)
print(f"Total Images: {total}")

📊 Final Dataset Summary
------------------------------
normal: 4414 images
diabetic_retinopathy: 10123 images
glaucoma: 569 images
------------------------------
Total Images: 15106

In [25]:
import os

dataset_path = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets"

for file in os.listdir(dataset_path):
    print(file)

APTOS
blood-vessel
Final_Dataset
full-fundus
metadata - standardized.csv
ODIR
optic-cup
optic-disc
RIM_ONE
spectral-oct
spectral-oct-cup
spectral-oct-disc
vessel-artery
vessel-vein

In [26]:
import pandas as pd

df = pd.read_csv(
    r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\metadata - standardized.csv"
)

print(df.head())
print(df.columns)

                     names  types type_expanded  isColor   original_name  \
0  OIA-ODIR-TEST-OFFLINE-1      0           NaN        1  1029_right.jpg
1  OIA-ODIR-TEST-OFFLINE-2      0           NaN        1   1049_left.jpg
2  OIA-ODIR-TEST-OFFLINE-4      0           NaN        1   1128_left.jpg
3  OIA-ODIR-TEST-OFFLINE-5      0           NaN        1  1179_right.jpg
4  OIA-ODIR-TEST-OFFLINE-6      0           NaN        1   1180_left.jpg

  patient_id                                    fundus fundus_od_seg  \
0        NaN  /full-fundus/OIA-ODIR-TEST-OFFLINE-1.png           NaN
1        NaN  /full-fundus/OIA-ODIR-TEST-OFFLINE-2.png           NaN
2        NaN  /full-fundus/OIA-ODIR-TEST-OFFLINE-4.png           NaN
3        NaN  /full-fundus/OIA-ODIR-TEST-OFFLINE-5.png           NaN
4        NaN  /full-fundus/OIA-ODIR-TEST-OFFLINE-6.png           NaN

  fundus_oc_seg bv_seg  ... cdr_expert4 refractive_dioptre_1  \
0           NaN    NaN  ...         NaN                  NaN
1           NaN    NaN  ...         NaN                  NaN
2           NaN    NaN  ...         NaN                  NaN
3           NaN    NaN  ...         NaN                  NaN
4           NaN    NaN  ...         NaN                  NaN

  refractive_dioptre_2 refractive_astigmatism phakic_or_pseudophakic  \
0                  NaN                    NaN                    NaN
1                  NaN                    NaN                    NaN
2                  NaN                    NaN                    NaN
3                  NaN                    NaN                    NaN
4                  NaN                    NaN                    NaN

  iop_perkins  iop_pneumatic  pachymetry axial_length  \
0         NaN            NaN         NaN          NaN
1         NaN            NaN         NaN          NaN
2         NaN            NaN         NaN          NaN
3         NaN            NaN         NaN          NaN
4         NaN            NaN         NaN          NaN

   visual_field_mean_defect
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN

[5 rows x 48 columns]
Index(['names', 'types', 'type_expanded', 'isColor', 'original_name',
       'patient_id', 'fundus', 'fundus_od_seg', 'fundus_oc_seg', 'bv_seg',
       'artery_seg', 'vein_seg', 'oct', 'oct_oc_seg', 'oct_od_seg', 'sex',
       'gender', 'age', 'eye', 'sbp', 'dbp', 'hr', 'iop', 'vcdr',
       'Unnamed: 24', 'notchI_present', 'notchS_present', 'notchN_present',
       'notchT_present', 'expert1_grade', 'expert2_grade', 'expert3_grade',
       'expert4_grade', 'expert5_grade', 'cdr_avg', 'cdr_expert1',
       'cdr_expert2', 'cdr_expert3', 'cdr_expert4', 'refractive_dioptre_1',
       'refractive_dioptre_2', 'refractive_astigmatism',
       'phakic_or_pseudophakic', 'iop_perkins', 'iop_pneumatic', 'pachymetry',
       'axial_length', 'visual_field_mean_defect'],
      dtype='str')

In [27]:
print(df["types"].value_counts())

types
 0    7549
 1    4767
-1     133
Name: count, dtype: int64

In [28]:
import os
import shutil
import pandas as pd

# Load SMDG metadata
df = pd.read_csv(
    r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\metadata - standardized.csv"
)

# Source folder containing all SMDG fundus images
source_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\full-fundus\full-fundus"

# Destination glaucoma folder
glaucoma_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset\glaucoma"

copied = 0
missing = 0

for _, row in df.iterrows():

    # Copy only glaucoma images (types = 1)
    if row["types"] != 1:
        continue

    # Get image filename
    filename = os.path.basename(row["fundus"])

    source = os.path.join(source_folder, filename)
    destination = os.path.join(glaucoma_folder, filename)

    if os.path.exists(source):
        shutil.copy2(source, destination)
        copied += 1
    else:
        missing += 1

print("✅ SMDG Glaucoma images copied successfully!")
print(f"Glaucoma images copied: {copied}")
print(f"Missing images: {missing}")

✅ SMDG Glaucoma images copied successfully!
Glaucoma images copied: 4767
Missing images: 0

In [29]:
import os

base_folder = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset"

print("📊 Final Dataset Summary")
print("-" * 35)

total = 0

for cls in ["normal", "diabetic_retinopathy", "glaucoma"]:
    folder = os.path.join(base_folder, cls)
    count = len([
        f for f in os.listdir(folder)
        if os.path.isfile(os.path.join(folder, f))
    ])
    print(f"{cls}: {count} images")
    total += count

print("-" * 35)
print(f"Total Images: {total}")

📊 Final Dataset Summary
-----------------------------------
normal: 4414 images
diabetic_retinopathy: 10123 images
glaucoma: 4767 images
-----------------------------------
Total Images: 19304

In [30]:
import os
from PIL import Image

dataset_path = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset"

corrupted = []

for category in os.listdir(dataset_path):
    category_path = os.path.join(dataset_path, category)

    for img in os.listdir(category_path):
        img_path = os.path.join(category_path, img)

        try:
            with Image.open(img_path) as image:
                image.verify()
        except Exception:
            corrupted.append(img_path)

print(f"Corrupted Images: {len(corrupted)}")

if corrupted:
    for img in corrupted:
        print(img)

Corrupted Images: 0

In [31]:
import os
from PIL import Image

# Original dataset
input_dataset = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Final_Dataset"

# Processed dataset
output_dataset = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Processed_Dataset"

# Create output folders
classes = ["normal", "diabetic_retinopathy", "glaucoma"]

for cls in classes:
    os.makedirs(os.path.join(output_dataset, cls), exist_ok=True)

target_size = (224, 224)

for cls in classes:

    input_folder = os.path.join(input_dataset, cls)
    output_folder = os.path.join(output_dataset, cls)

    count = 0

    for image_name in os.listdir(input_folder):

        input_path = os.path.join(input_folder, image_name)
        output_path = os.path.join(output_folder, image_name)

        try:
            img = Image.open(input_path)
            img = img.convert("RGB")
            img = img.resize(target_size)

            img.save(output_path)

            count += 1

        except Exception:
            print("Skipped:", image_name)

    print(f"{cls}: {count} images resized.")

print("\n✅ Dataset resized successfully!")

normal: 4414 images resized.
diabetic_retinopathy: 10123 images resized.
glaucoma: 4767 images resized.

✅ Dataset resized successfully!

In [32]:
import os

processed_dataset = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Processed_Dataset"

print("📊 Processed Dataset Summary")
print("-"*35)

total = 0

for cls in os.listdir(processed_dataset):
    folder = os.path.join(processed_dataset, cls)

    count = len(os.listdir(folder))

    print(f"{cls}: {count}")

    total += count

print("-"*35)
print("Total:", total)

📊 Processed Dataset Summary
-----------------------------------
diabetic_retinopathy: 10123
glaucoma: 4767
normal: 4414
-----------------------------------
Total: 19304

In [33]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in C:\Users\nonay\AppData\Roaming\Python\Python314\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\nonay\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\nonay\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\nonay\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\nonay\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
import os
import shutil
from sklearn.model_selection import train_test_split

# Source folder (resized dataset)
source_dataset = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Processed_Dataset"

# Destination folder
split_dataset = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Split_Dataset"

classes = ["normal", "diabetic_retinopathy", "glaucoma"]

# Create folder structure
for split in ["train", "validation", "test"]:
    for cls in classes:
        os.makedirs(os.path.join(split_dataset, split, cls), exist_ok=True)

for cls in classes:

    source_folder = os.path.join(source_dataset, cls)

    images = os.listdir(source_folder)

    # 80% train, 20% temp
    train_imgs, temp_imgs = train_test_split(
        images,
        test_size=0.20,
        random_state=42,
        shuffle=True
    )

    # 10% validation, 10% test
    val_imgs, test_imgs = train_test_split(
        temp_imgs,
        test_size=0.50,
        random_state=42,
        shuffle=True
    )

    # Copy training images
    for img in train_imgs:
        shutil.copy2(
            os.path.join(source_folder, img),
            os.path.join(split_dataset, "train", cls, img)
        )

    # Copy validation images
    for img in val_imgs:
        shutil.copy2(
            os.path.join(source_folder, img),
            os.path.join(split_dataset, "validation", cls, img)
        )

    # Copy test images
    for img in test_imgs:
        shutil.copy2(
            os.path.join(source_folder, img),
            os.path.join(split_dataset, "test", cls, img)
        )

    print(f"{cls} completed!")

print("\n✅ Dataset split successfully!")

normal completed!
diabetic_retinopathy completed!
glaucoma completed!

✅ Dataset split successfully!

In [35]:
import os

split_dataset = r"D:\DR AND GLAUCOMA DETECTION PROJECT\datasets\Split_Dataset"

for split in ["train", "validation", "test"]:

    print(f"\n📂 {split.upper()}")

    total = 0

    for cls in ["normal", "diabetic_retinopathy", "glaucoma"]:

        count = len(os.listdir(os.path.join(split_dataset, split, cls)))

        print(f"{cls}: {count}")

        total += count

    print("Total:", total)

📂 TRAIN
normal: 3531
diabetic_retinopathy: 8098
glaucoma: 3813
Total: 15442

📂 VALIDATION
normal: 441
diabetic_retinopathy: 1012
glaucoma: 477
Total: 1930

📂 TEST
normal: 442
diabetic_retinopathy: 1013
glaucoma: 477
Total: 1932